[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Joker Layers Patch
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'if self.config.center.soul_pos and (self.config.center.discovered or self.bypass_discovery_center) then'
match_indent = true
position = "before"
payload = '''
if beepsterr and beepsterr.bargainbin and beepsterr.bargainbin.util and beepsterr.bargainbin.util.setup_card_layers then
    beepsterr.bargainbin.util.setup_card_layers(self)
end
'''

# layer table doesn't have VT, since it has it's own children
# (should it just add self.children['layer_'..k] ? It'd be less prone to breaking...)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
        for k, v in pairs(self.children) do
            v.VT.scale = self.VT.scale
        end
'''
match_indent = true
position = "at"
payload = '''
    for k, v in pairs(self.children) do
        if k ~= "layers" then
            v.VT.scale = self.VT.scale
        end
    end
'''

# intercept call to draw
[[patches]]
[patches.regex]
target = "card.lua"
pattern = "(k \\~= \"soul_parts\")"
position = 'at'
payload = '$1 and not v.no_draw '
times = 1