name: Create Release

on:
  workflow_dispatch: # This allows us to manually trigger the workflow
  push:
    branches:
      - master
    paths:
      - 'BargainBin.json'  # This ensures the workflow only runs if BargainBin.json changes

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we fetch all history for all branches and tags

      - name: Check for version change
        id: version_check
        run: |
          OLD_VERSION=$(git tag --sort=-v:refname | grep -o 'v[0-9]*\.[0-9]*\.[0-9]*' | head -n 1 | cut -c 2-)
          NEW_VERSION=$(jq -r '.version' BargainBin.json)
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "::set-output name=version_changed::true"
            echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          fi

      - name: Remove unwanted directories
        run: |
          rm -rf ./.idea
          rm -rf ./.git
          rm -rf ./lovely_disabled
          rm -rf ./assets/dev

      - name: Zip the content
        run: zip -r release.zip ./*

      - name: Create Release
        if: steps.version_check.outputs.version_changed == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *
            **/*
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
