name: Create dist zip

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Remove unwanted directories
        run: |
          rm -rf ./.idea
          rm -rf ./.git
          rm -rf ./lovely_disabled
          rm -rf ./assets/dev

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./
